language: generic
install:
- npm install gitbook-cli -g
script:
- gitbook install
- gitbook build
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: _book
 on:
   branch: master
